
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := gps.conf
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH  := $(TARGET_OUT_VENDOR)/etc/
LOCAL_SRC_FILES := gps.conf
LOCAL_POST_INSTALL_CMD := ln -sf /system/vendor/etc/$(LOCAL_MODULE) $(TARGET_OUT_ETC)/$(LOCAL_MODULE)

include $(BUILD_PREBUILT)

